language: node_js
node_js:
  - '10'
dist: trusty
sudo: required
branches:
  only:
    - master
before_script:
  - npm install -g @angular/cli
script:
  - ng lint
  - ng build --prod --base-href https://wojtrawi.github.io/emersoft-task/
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/emersoft-task
  on:
    branch: master
